# Generated by Django 2.0.7 on 2018-08-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburban_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='content',
        ),
        migrations.AddField(
            model_name='definition',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='example',
            field=models.TextField(blank=True),
        ),
    ]
