# Generated by Django 2.0.7 on 2018-08-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburban_dictionary', '0002_auto_20180805_0533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['term']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='name',
            new_name='term',
        ),
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='definition',
            name='example',
            field=models.TextField(),
        ),
    ]
