# Generated by Django 2.0.7 on 2018-08-05 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suburban_dictionary', '0003_auto_20180805_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='suburban_dictionary.Term'),
        ),
    ]
