# Generated by Django 2.0.7 on 2018-08-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suburban_dictionary', '0004_auto_20180805_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='definition',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
