# Generated by Django 2.0.7 on 2018-08-05 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suburban_dictionary', '0005_auto_20180805_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='definition',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
