# Generated by Django 2.0.7 on 2018-08-08 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suburban_dictionary', '0008_remove_definition_edited_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='definition',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='definition',
            name='likes',
        ),
        migrations.AddField(
            model_name='definition',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
